/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wkmmsowovsukqunkpybx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrbW1zb3dvdnN1a3F1bmtweWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczOTEzMTcsImV4cCI6MjA4Mjk2NzMxN30.vnlmIs3rgt-euh-aomU0EyGH3zm_z5LXvi8QNuYLs8o"